save: fix saving not updating sg format
rr-/Tomb1Main pull request #444
Opened 2022-02-18 21:13 UTC by rr-

#### Checklist

- [x] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes

#### Descripton

#442

2022-02-18 21:18 UTC, walkawayy commented
Could you publish a build here so @Richard-L and @rapora9 can test? I'm unable to currently.

2022-02-18 21:35 UTC, walkawayy commented
Ok I found the old publish release command. But the build fails:
```
| FAILED: Tomb1Main.exe.p/src_game_savegame.c.obj 
| /usr/bin/i686-w64-mingw32-gcc -ITomb1Main.exe.p -I. -I.. -I../src -I/ext//include -I/ext/include/SDL2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -Wno-unused -D_GNU_SOURCE '-DVERSION="T1M 2.6.3-1-ga1e5ad3"' -Dmain=SDL_main -MD -MQ Tomb1Main.exe.p/src_game_savegame.c.obj -MF Tomb1Main.exe.p/src_game_savegame.c.obj.d -o Tomb1Main.exe.p/src_game_savegame.c.obj -c ../src/game/savegame.c
| ../src/game/savegame.c: In function ‘Savegame_Save’:
| ../src/game/savegame.c:395:26: error: ‘GAME_INFO’ {aka ‘struct GAME_INFO’} has no member named ‘format’
|   395 |                 game_info->format = strategy->format;
|       |                          ^~
```

2022-02-18 21:39 UTC, walkawayy requested changes

2022-02-18 21:39 UTC, walkawayy commented on src/game/savegame.c
> +                game_info->current_save_slot = slot_num;
`GAME_INFO` doesn't have a `format`.

2022-02-18 22:12 UTC, walkawayy commented
[Tomb1Main-2.6.3-1-g3a6e85d_test_death.zip](https://github.com/rr-/Tomb1Main/files/8100725/Tomb1Main-2.6.3-1-g3a6e85d_test_death.zip)

2022-02-18 22:31 UTC, Rapora9 commented
This time there is no error message at all, the game just crashes.
What I tested: load legacy save -> save into an empty slot -> die.

2022-02-18 23:03 UTC, rr- commented
[Tomb1Main-2.6.3-1-gb4df71d.zip](https://github.com/rr-/Tomb1Main/files/8100925/Tomb1Main-2.6.3-1-gb4df71d.zip)

2022-02-20 06:30 UTC, walkawayy approved these changes

2022-02-20 06:32 UTC, walkawayy commented
LGTM

2022-02-20 08:54 UTC, merged