Renames continued
rr-/Tomb1Main pull request #524
Opened 2022-04-22 22:17 UTC by rr-

#### Checklist

- [x] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

#521

2022-05-04 17:01 UTC, walkawayy requested changes
Looks good. Left two comments.

2022-05-04 18:10 UTC, rr- commented on src/game/matrix.c
> +#include "game/matrix.h"
I think it would make sense to get rid of that folder entirely, WDYT?

2022-05-04 18:11 UTC, rr- commented on src/game/items.h
> +void Effect_InitialiseArray(void);
I would be  inclined to move them to game/effects.c. game/effects/ contains specialized implementations of various effects, similar to ai/ for objects. WDYT?

2022-05-04 18:12 UTC, walkawayy commented on src/game/matrix.c
> +#include "game/matrix.h"
I'm fine with that.

2022-05-04 18:13 UTC, walkawayy commented on src/game/items.h
> +void Effect_InitialiseArray(void);
That sounds good.

2022-05-04 18:14 UTC, walkawayy commented on src/game/matrix.c
> +#include "game/matrix.h"
I like that.

2022-05-05 10:01 UTC, rr- commented on src/game/matrix.c
> +#include "game/matrix.h"
Done

2022-05-05 10:01 UTC, rr- commented on src/game/items.h
> +void Effect_InitialiseArray(void);
Done

2022-05-05 10:44 UTC, rr- commented
I also moved line-of-sight utilities to `los.c`.

2022-05-06 08:18 UTC, rr- commented
@walkawayy are we good with this batch?

2022-05-06 12:47 UTC, walkawayy commented
Yep!

2022-05-06 13:22 UTC, merged