Ability to decide whether active or newly triggered (runaway) Pierre is despawned
rr-/Tomb1Main pull request #530
Opened 2022-04-29 17:13 UTC by Rapora9

#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

If there is a runaway Pierre active and the player tries to trigger another runaway Pierre, the new Pierre will be despawned immediately while the old one remains. **With this change**, the player can change this behaviour so that old Pierre will be despawned and new Pierre remains. This way the player gets to face all instances of Pierre even if they did not make the old Pierre run before trying to trigger a new one.
...

2022-04-29 18:29 UTC, walkawayy requested changes
You need to add something like this to `Tomb1Main.json5` so the user can enable/disable this setting.
```
// Fixes Pierre blah blah blah
"fix_pierre_spawn": true,
```

Can you also open an issue to describe the original game's Pierre behavior and why this is an improvement? Your videos you posted in Discord showing the difference would be useful to include in the issue.

2022-04-29 18:29 UTC, walkawayy commented on src/game/objects/ai/pierre.c
> +
You can remove this blank line.

2022-04-29 18:31 UTC, walkawayy commented on CHANGELOG.md
> +- added the ability to make new Pierre replace an old active (runaway) Pierre
Also can you update this entry to include the issue number when that's opened? Also this line can probably be added to the README too (without the issue number, check out the other entries in it)

2022-04-29 20:06 UTC, Rapora9 commented on src/game/objects/ai/pierre.c
> +
issued opened #532. Blank line removed.

2022-04-29 20:07 UTC, Rapora9 commented on CHANGELOG.md
> +- added the ability to make new Pierre replace an old active (runaway) Pierre
Changelog and readme updated

2022-05-04 14:51 UTC, Richard-L commented
Have build?

I need to learn how to make them myself at some point

2022-05-04 14:58 UTC, rr- commented
> Have build?
> 
> I need to learn how to make them myself at some point

https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#compiling-on-windows

2022-05-04 16:32 UTC, walkawayy commented
Here is the build @Richard-L 

[Tomb1Main-2.8-5-gf6a28ec_pierre.zip](https://github.com/rr-/Tomb1Main/files/8622281/Tomb1Main-2.8-5-gf6a28ec_pierre.zip)

2022-05-14 09:48 UTC, rr- commented
Any updates on testing?
I think this can be merged, no?

2022-05-14 10:19 UTC, Richard-L commented
Hmm sorry not really. I spoke about it some more with @Rapora9 over DM and the topic honestly escaped me. I cannot see how a non-TRLE player like me would be affected by this, and I think we agree that speedrun tactics around Pierre should not be broken.

2022-05-14 11:17 UTC, Rapora9 commented
> Any updates on testing? I think this can be merged, no?

Yes, I think it's good to go. I haven't spotted any issues anymore.

2022-05-15 19:19 UTC, rr- commented
Merged manually to the develop branch.

2022-05-15 19:19 UTC, closed without merging